# Generated by Django 4.0 on 2022-01-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_engine', '0003_userdetail_user_alter_userdetail_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupwisepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_engine.group'),
        ),
        migrations.AlterField(
            model_name='rolewisepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_engine.role'),
        ),
    ]
