# Generated by Django 4.0 on 2022-01-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_engine', '0004_alter_groupwisepermission_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='group',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='group',
            field=models.ManyToManyField(related_name='groups', to='accounts_engine.Group'),
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='role',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='role',
            field=models.ManyToManyField(related_name='roles', to='accounts_engine.Role'),
        ),
    ]
