# Generated by Django 4.0 on 2022-01-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_engine', '0005_remove_userdetail_group_userdetail_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupwisepermission',
            old_name='role',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='permission',
            name='section',
            field=models.CharField(choices=[('0', 'profile'), ('1', 'setting'), ('2', 'driver'), ('3', 'vehicle'), ('4', 'journey'), ('4', 'hsse'), ('5', 'reports')], default='0', max_length=10),
        ),
    ]
