# Generated by Django 3.2.10 on 2022-01-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('education', models.CharField(max_length=200)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('driving_licence_num', models.CharField(max_length=16)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('driving_licence_issue_date', models.DateField()),
                ('driving_licence_expiry_date', models.DateField()),
                ('hgv_licence_issue_date', models.DateField()),
                ('hazard_issue_date', models.DateField()),
                ('address', models.TextField()),
                ('id_card_type', models.CharField(choices=[('aadhar card', 'Aadhar Card'), ('Election Card', 'Election Card'), ('passport', 'Passport'), ('driving licencse', 'Driving Licencse')], default='aadhar card', max_length=100)),
                ('joining_date', models.DateField()),
                ('interviewed_by', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('0', 'In Active'), ('1', 'Active'), ('2', 'On Leave')], default='1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
