# Generated by Django 3.2.10 on 2022-01-04 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts_engine.customuser'),
            preserve_default=False,
        ),
    ]
