# Generated by Django 3.2.10 on 2022-01-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_engine', '0002_driver_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='bank_ac_holder_name',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_ac_number',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_name',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='blood_group',
            field=models.CharField(choices=[('0', 'O +ve'), ('1', 'O -ve'), ('2', 'A +ve'), ('3', 'A -ve'), ('4', 'B +ve'), ('5', 'B -ve'), ('6', 'AB +ve'), ('7', 'AB -ve')], default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='card_number',
            field=models.CharField(default='as', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='ifsc_code',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='mobile_number',
            field=models.CharField(default='asd', max_length=10),
            preserve_default=False,
        ),
    ]
