# Generated by Django 3.2.10 on 2022-01-04 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_engine', '0003_auto_20220104_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_driver_test_date', models.DateField(blank=True, null=True)),
                ('medical_test_date', models.DateField(blank=True, null=True)),
                ('first_aid_date', models.DateField(blank=True, null=True)),
                ('fire_fighting_date', models.DateField(blank=True, null=True)),
                ('company_induction_date', models.DateField(blank=True, null=True)),
                ('ddt_date', models.DateField(blank=True, null=True)),
                ('shell_induction_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='driver_engine.driver')),
                ('senior_driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senior_drivers', to='driver_engine.driver')),
            ],
        ),
    ]
