# Generated by Django 3.2.10 on 2022-01-29 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_engine', '0004_driverrecruitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverBehaviourTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1a', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q1b', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q1c', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q1d', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q2a', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q2b', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q2c', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q2d', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q3a', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q3b', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q3c', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q3d', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q4a', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q4b', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q4c', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('q4d', models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drivers_behaviour', to='driver_engine.driver')),
            ],
        ),
    ]
