# Generated by Django 3.2.10 on 2022-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_engine', '0006_driver_hiring_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_image',
            field=models.ImageField(default=0, upload_to='media/profile_pic/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='hazard_image',
            field=models.ImageField(default=0, upload_to='media/hazard/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='licencse_image',
            field=models.ImageField(default=0, upload_to='media/dl/'),
            preserve_default=False,
        ),
    ]
