# Generated by Django 3.2.10 on 2022-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_engine', '0007_auto_20220129_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbehaviourtest',
            name='q5a',
            field=models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='driverbehaviourtest',
            name='q5b',
            field=models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='driverbehaviourtest',
            name='q5c',
            field=models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='driverbehaviourtest',
            name='q5d',
            field=models.CharField(choices=[('', 'SELECT'), (5, 'Agree'), (3, 'Neutral'), (1, 'Disagree')], default='', max_length=10),
        ),
    ]
