# Generated by Django 3.2.10 on 2022-01-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_engine', '0008_auto_20220129_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q1a',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q1b',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q1c',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q1d',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q2a',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q2b',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q2c',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q2d',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q3a',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q3b',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q3c',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q3d',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q4a',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q4b',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q4c',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q4d',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q5a',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q5b',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q5c',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverbehaviourtest',
            name='q5d',
            field=models.CharField(choices=[('', 'SELECT'), ('5', 'Agree'), ('3', 'Neutral'), ('1', 'Disagree')], default='', max_length=10),
        ),
    ]
