# Generated by Django 3.2.10 on 2022-01-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_engine', '0009_auto_20220129_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrecruitment',
            name='ddt_grade',
            field=models.CharField(choices=[('', 'SELECT'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='driverrecruitment',
            name='ddt_image',
            field=models.ImageField(default=0, upload_to='media/ddt/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverrecruitment',
            name='induction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverrecruitment',
            name='induction_image',
            field=models.ImageField(default=0, upload_to='media/induction/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverrecruitment',
            name='past_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverrecruitment',
            name='past_experience_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverrecruitment',
            name='senior_driver_test',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverrecruitment',
            name='shell_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driverrecruitment',
            name='shell_induction_image',
            field=models.ImageField(default=0, upload_to='media/ddt/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='hiring_status',
            field=models.CharField(choices=[('0', 'In process'), ('1', 'On Hold'), ('2', 'Selected'), ('3', 'Rejected')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverrecruitment',
            name='shell_induction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
