# Generated by Django 3.2.10 on 2022-02-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_engine', '0010_auto_20220129_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='blood_group',
            field=models.CharField(choices=[('', 'Select Blood Group'), ('0', 'O +ve'), ('1', 'O -ve'), ('2', 'A +ve'), ('3', 'A -ve'), ('4', 'B +ve'), ('5', 'B -ve'), ('6', 'AB +ve'), ('7', 'AB -ve')], max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='can_read',
            field=models.BooleanField(choices=[('', 'CAN READ?'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='can_write',
            field=models.BooleanField(choices=[('', 'CAN WRITE?'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='hazard_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hazard/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licencse_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/dl/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('0', 'In Active'), ('1', 'Active'), ('2', 'On Leave')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverrecruitment',
            name='ddt_grade',
            field=models.CharField(blank=True, choices=[('', 'SELECT'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driverrecruitment',
            name='ddt_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/ddt/'),
        ),
        migrations.AlterField(
            model_name='driverrecruitment',
            name='induction_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/induction/'),
        ),
        migrations.AlterField(
            model_name='driverrecruitment',
            name='senior_driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior_drivers', to='driver_engine.driver'),
        ),
    ]
