# Generated by Django 3.2.10 on 2022-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_engine', '0012_auto_20220205_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='on_leave',
            field=models.BooleanField(choices=[('', 'ON LEAVE'), (True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('0', 'In Active'), ('1', 'Active')], default='0', max_length=10),
        ),
    ]
