# Generated by Django 3.2.10 on 2022-02-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_engine', '0014_driverleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverleave',
            name='status',
            field=models.CharField(default='-1', max_length=20),
        ),
    ]
