# Generated by Django 3.2.10 on 2022-02-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_engine', '0015_alter_driverleave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverleave',
            name='status',
            field=models.CharField(choices=[(0, 'Not Reviewed'), (1, 'Accepted'), (2, 'Rejected')], default='0', max_length=20),
        ),
    ]
